const questions: string[] = [
"People can rarely upset you.",
"You often talk about your own feelings and emotions.",
"You often think about what you should have said in a conversation long after it has taken place.",
"When it comes to making life-changing choices, you mostly listen to your heart rather than your head.",
"When at a social event, you rarely try to introduce yourself to new people and mostly talk to the ones you already know.",
"You feel comfortable just walking up to someone you find interesting and striking up a conversation.",
"You have a careful and methodical approach to life.",
"When in a group of people you do not know, you have no problem jumping right into their conversation.",
"Even when you have planned a particular daily routine, you usually just end up doing what you feel like at any given moment.",
"You feel more drawn to places with a bustling and busy atmosphere than to more quiet and intimate ones.",
"You often contemplate the reasons for human existence or the meaning of life.",
"Spending time in a dynamic atmosphere with lots of people around quickly makes you feel drained and in need of a getaway.",
"You often drift away into daydreaming about various ideas or scenarios.",
"You often have a hard time understanding other people’s feelings.",
"You still honor the commitments you have made even if you have a change of heart.",
"At parties and similar events you can mostly be found farther away from the action.",
"You often find it difficult to relate to people who let their emotions guide them.",
"You often spend time exploring unrealistic yet intriguing ideas.",
"When looking for a movie to watch, you can spend ages browsing the catalog.",
"You are very affectionate with people you care about.",
"After a long and exhausting week, a fun party is just what you need.",
"You frequently find yourself wondering how technological advancement could change everyday life.",
"Your emotions control you more than you control them.",
"In your opinion, it is sometimes OK to step on others to get ahead in life.",
"If you make a mistake, you tend to start doubting yourself, your abilities, or your knowledge.",
"You often rely on other people to be the ones to start a conversation and keep it going.",
"You see yourself as more of a realist than a visionary.",
"You usually prefer to get your revenge rather than forgive.",
"When starting to work on a project, you prefer to make as many decisions upfront as possible.",
"You rarely feel insecure.",
"Your travel plans are more likely to look like a rough list of ideas than a detailed itinerary.",
"You can stay calm under a lot of pressure.",
"If you have to temporarily put your plans on hold, you make sure it is your top priority to get back on track as soon as possible.",
"When you know someone thinks highly of you, you also wonder how long it will be until they become disappointed in you.",
"The time you spend by yourself often ends up being more interesting and satisfying than the time you spend with other people.",
"You cannot imagine yourself dedicating your life to the study of something that you cannot see, touch, or experience.",
"If your friend is sad about something, your first instinct is to support them emotionally, not try to solve their problem.",
"You often make decisions on a whim.",
"You often put special effort into interpreting the real meaning or the message of a song or a movie.",
"You rarely dwell on your regrets.",
"When you sleep, your dreams tend to be bizarre and fantastical.",
"You always consider how your actions might affect other people before doing something.",
"You rarely think back on the choices you made and wonder what you could have done differently.",
"Your mood can change very quickly.",
"You rarely worry if you made a good impression on someone you met.",
"You look after yourself first, and others come in second.",
"It would be a challenge for you to spend the whole weekend all by yourself without feeling bored.",
"You like discussing different views and theories on what the world could look like in the future.",
"You always know exactly what you want.",
"You tend to focus on present realities rather than future possibilities.",
"You usually lose interest in a discussion when it gets philosophical.",
"You find it easy to empathize with a person who has gone through something you never have.",
"You are more of a detail-oriented than a big picture person.",
"You are still bothered by the mistakes you made a long time ago.",
"You have got detailed education or career development plans stretching several years into the future.",
"When in a public place, you usually stick to quieter and less crowded areas.",
"Your personal work style is closer to spontaneous bursts of energy than to organized and consistent efforts.",
"You would never let yourself cry in front of others.",
"You are dedicated and focused on your goals, only rarely getting sidetracked.",
"You enjoy vibrant social events with lots of people.",
]

export default questions